### ISSUE TITLE
It's hard to think of an equal because everyone I think of is so much awesomer than me

### ISSUE THREAD

**Issue by leahbannon** [techladymafia/oneforone#4]
So, impostor syndrome. I keep trying to think of someone and then I instantly start thinking about how much more awesome they are than me. I worry that this might be a barrier for other woman to contribute, too, so I'm trying to solve it this way: I'm listing some important qualifications about me. If you'd like to be my one for one, please comment. DON'T BE SHY.
- I know digital strategy, some HTML/CSS, and I'm familiar with APIs and GitHub.
- I'm good at strategic communications and digital gov strategy.
- I organize some great tech events.

**Comment by ErieMeyer** [comment]
Leah! Just name someone who could do your job as well as you (if not better!) who has those characteristics. Don't stress if you think they are amazing x87848574
